monthly_income = input ("Enter your monthly income: ")
monthly_expenses = input("Enter your monthly expense: ")
mmonthly_savings = float(monthly_income) - float(monthly_expenses)
projected_savings = (mmonthly_savings) * 12 + (mmonthly_savings * 12 * 0.05)
print("Your projected saving after one year is:", projected_savings)